# Generated by Django 3.1.7 on 2021-03-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender_user',
            name='UrlToImage',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='recommender_user',
            name='author',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recommender_user',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='recommender_user',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='recommender_user',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recommender_user',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='recommender_user',
            name='url',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
