# Generated by Django 3.1.7 on 2021-03-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20210320_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommender_user',
            name='source',
        ),
    ]
