# Generated by Django 3.1.7 on 2021-03-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscat',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
