# Generated by Django 3.1.7 on 2021-03-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryNews', '0002_newscat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscat',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
