# Generated by Django 3.1.7 on 2021-03-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryNews', '0005_auto_20210310_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscat',
            name='author',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newscat',
            name='category',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='newscat',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='newscat',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newscat',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
