# Generated by Django 3.1.7 on 2021-03-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryNews', '0006_auto_20210315_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscat',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
