# Generated by Django 3.1.7 on 2021-03-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topheadline_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('UrlToImage', models.ImageField(max_length=1000, upload_to='')),
                ('PublishedAt', models.DateField()),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
