# Generated by Django 3.1.7 on 2021-03-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopHeadlines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topheadline_detail',
            name='source',
        ),
        migrations.AlterField(
            model_name='topheadline_detail',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='topheadline_detail',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
