# Generated by Django 3.1.7 on 2021-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopHeadlines', '0003_topheadline_detail_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadline_detail',
            name='UrlToImage',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='topheadline_detail',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topheadline_detail',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='topheadline_detail',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='topheadline_detail',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topheadline_detail',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='topheadline_detail',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
