# Generated by Django 3.1.7 on 2021-03-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopHeadlines', '0004_auto_20210301_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadline_detail',
            name='id',
            field=models.DecimalField(decimal_places=2, max_digits=5, primary_key=True, serialize=False),
        ),
    ]
