# Generated by Django 3.1.7 on 2021-03-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopHeadlines', '0006_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cat',
        ),
    ]
