# Generated by Django 3.1.7 on 2021-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopHeadlines', '0007_delete_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadline_detail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
